# -*- coffee -*- -p
author: YC <yinso.chen@gmail.com>
name: doclet
description: A simple "document" loader library
version: 0.1.1
repository:
  type: git
  url: git://github.com/yinso/doclet.git
main: ./lib/loader
engines:
  node: '>= 0.8.4'
scripts:
  test: make test
  prepublish: make
dependencies:
  mockquery: =0.2.5
  underscore: =1.7.0
  loglet: '>=0.1.0'
  marked: =0.3.2
  js-yaml: =3.2.2
  yaml-front-matter: =3.0.1
  coffee-script: =1.8.0
  pretty-data: =0.40.0
  filelet: '>=0.1.0'
  funclet: '>=0.1.1'
devDependencies:
  testlet: '>= 0.2.0'
  coffee-bean: =0.3.0
